### ISSUE TITLE
Typo in 

### ISSUE THREAD

**Issue by code-in-progress** [philkra/elastic-apm-php-agent#1]
Hey, great start on this (I was actually going to roll my own, but you beat me to it). Found a typo in /philkra/elastic-apm-php-agent/src/Middleware/Connector.php

private function getRequestHeaders() : array {
    // Default Headers Set
    $headers = [
      'Content-Type'     => 'application/json',
      'Content-Encoding' => 'deflate',
      'User-Agent'       => **spritnf**( 'elasticapm-php/%s', Agent::VERSION ),
    ];

    // Add Secret Token to Header
    if( $this->config->get( 'secretToken' ) !== null ) {
      $headers['Authorization'] = sprintf( 'Bearer %s', $this->config['secretToken'] ); 
    }

    return $headers;
  }

**Comment by philkra** [comment]
thanks for the feedback! this is fixed
