### ISSUE TITLE
Can't Get Agent to Work

### ISSUE THREAD

**Issue by Haddad1** [philkra/elastic-apm-php-agent#104]
Hey, 

So im new to this APM overall, so im starting with a small php file to test things out but even that is not working, here is what i have:

index.php file:
```
<?php
 
$config = [
    'appName'     => 'APM Test Server',
    'appVersion'  => '1.0',
    'serverUrl'   => 'http://serverip:8200',
    'hostname'    => 'APM Server',
    'env'         => ['DOCUMENT_ROOT'],
];
$agent = new PhilKra\Agent($config);

require 'vendor/autoload.php';
echo "hello";
sleep(5);
echo "goodbye";
?>
```

and this is the error that i get whenever i try to run the php script:

`PHP Fatal error:  Uncaught Error: Class 'PhilKra\Agent' not found in /home/ubuntu/test/index.php:10
Stack trace:
#0 {main}
  thrown in /home/ubuntu/test/index.php on line 10`

this is how my directory looks like:

`PhilKra/  composer.json  composer.lock  elastic-apm-php-agent/  index.php  vendor/`

what am i missing here?

Any help or guidance is greatly appreciated.

Cheers!

**Comment by philkra** [comment]
you need to include the `autoloader` prior to using the Agent as that file contains the boostraping and class autoloader. Generally a good practice to _write_ this as the first line of code ..

```php
<?php
 
require 'vendor/autoload.php'; // must be first

$config = [
    'appName'     => 'APM Test Server',
    'appVersion'  => '1.0',
    'serverUrl'   => 'http://serverip:8200',
    'hostname'    => 'APM Server',
    'env'         => ['DOCUMENT_ROOT'],
];
$agent = new PhilKra\Agent($config);

echo "hello";
sleep(5);
echo "goodbye";
```

**Comment by Haddad1** [comment]
Oh wow that actually worked but now how can i tell if the "stats" were sent to the ELK server?

**Comment by philkra** [comment]
please use the [examples](https://github.com/philkra/elastic-apm-php-agent#examples) to get ramped up on usage of the agent and use the official documentation on deploying the Elastic Stack.

**Comment by Haddad1** [comment]
I have my ELK stack setup and running with no issues, Kibana and ES and Logstash are all working fine. But can you be more specific as to where the examples are located at?

Thank you bro!
