### ISSUE TITLE
Possible to convert debug_backtrace() into span stack trace

### ISSUE THREAD

**Issue by MattRiddell** [philkra/elastic-apm-php-agent#108]
Hi,

Quick question.  I see the example which creates a stack trace manually for a span.

Is there any way to convert a stack trace created by debug_backtrace into a format that can be used in a span?

I've had a bit of a search around and there doesn't seem to be any questions or answers along this line.

If I do:

`$spanSt->setStackTrace(debug_backtrace());`

it causes:

`[Sat Nov 09 19:19:07.447727 2019] [php7:error] [pid 24024] [client 127.0.0.1:52194] PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ClientException: Client error: `POST http://apm:8200/intake/v2/events` resulted in a `400 Bad Request` response:\n{\n  "accepted": 5,\n  "errors": [\n    {\n      "message": "error validating JSON document against schema: I[#] S[#] doesn' (truncated...)\n in /Users/matt/Sites/x/private/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113\nStack trace:\n#0 /Users/matt/Sites/x/private/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))\n#1 /Users/matt/Sites/x/private/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))\n#2 /Users/matt/Sites/x/private/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(GuzzleHttp\\Psr7\\Response), Array)\n#3 /Users/matt/Sites/x/pri in /Users/matt/Sites/x/private/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113, referer: http://pv.com/admin/system_reports/unfulfillable.php`

**Comment by philkra** [comment]
Hi Matt, the error is happening because the apm-server is not able to _understand_ the format of the stack trace (see [spec](https://github.com/elastic/apm-server/blob/master/docs/spec/stacktrace_frame.json)). Would like to open a PR for wrapping `debug_backtrace()` to the stack trace format needed?

**Comment by MattRiddell** [comment]
Where would be the best place to put it?

**Comment by MattRiddell** [comment]
To be fair, it doesn't match up great - we don't get code or anything from debug_backtrace, but in its simplest form this works:

```php
/**
 * @param $full_backtrace
 * @return array
 */
function convertBacktraceToStackFrame($full_backtrace) {
    $return_value = array();
    if (!is_array($full_backtrace)) {
        return $return_value;
    }
    foreach ($full_backtrace as $single_backtrace) {
        $stacktrace             = array();
        $stacktrace['abs_path'] = $single_backtrace['file'];
        $stacktrace['filename'] = basename($single_backtrace['file']);
        $stacktrace['function'] = $single_backtrace['function'] ?? null;
        $stacktrace['lineno']   = $single_backtrace['line'] ?? null;
        $stacktrace['module']   = $single_backtrace['class'] ?? null;
        $stacktrace['vars']     = $single_backtrace['args'] ?? null;
        $return_value[]         = $stacktrace;
    }
    return $return_value;
}
```

**Comment by philkra** [comment]
> Where would be the best place to put it?

My first idea would be to put the method as helper, e.g. `Helpers\Stacktrace` with a static method `convertBacktraceToStackFrame(?array $backtrace)`. What do you think?

> we don't get code or anything from debug_backtrace

that's what a stacktrace is for ;) I gives you a "path" thru the called app stack to reconstruct.

**Comment by MattRiddell** [comment]
Ok, yep sounds good.

**Comment by MattRiddell** [comment]
I added a pull request

**Comment by philkra** [comment]
closing in favour of PR #112
