### ISSUE TITLE
404 on POST /v2/transactions

### ISSUE THREAD

**Issue by gustavo-maxmilhas** [philkra/elastic-apm-php-agent#109]
Hi all,

Im trying to make local tests for the apm server. I setup a elastic + kibana stack on docker and now i want to make my application start sending requests to the apm server.

For some reason, i am getting a 404 error when the POST is made to the /v2/transactions url.

The application itself is also running on a docker host. My config is:

`
$agent = new Agent( 
[ 
    'appName' => 'api-checkout',
    'serverUrl' => 'http://192.168.122.1:8200',
    'apmVersion' => 'v2'
] );
`

If i go inside the docker host and try to simulate the same POST that is made from the application:
`curl -v -XPOST -H 'Content-Type: application/json' http://192.168.122.1:8200/intake/v2/events`

i get the error:
`{
  "accepted": 0,
  "errors": [
    {
      "message": "EOF while reading metadata"
    }
  ]
}
`

But, inside the application the error is 404.
Does anyone know if i am doing something wrong?

APM-SERVER vesion: 7.4.2
Application PHP version: 7.1

The apm server and the elastic are OK! I can see the connection messages in kibana from the apm server and the apm-server test on the apm configuration in kibana is green.

Thank you

**Comment by philkra** [comment]
What version of this lib are you using?

**Comment by gustavo-maxmilhas** [comment]
Sorry, i left that out
Lib Version: 6.5.8

**Comment by philkra** [comment]
Ok, that's the problem. The `6.x` version of the lib only supports the `v1` intake API of the APM server and with the `7.x` release, the `v2` intake API is supported, which also correlates with your APM server version. The lib is currently in an rc state, but will be released this week, see last https://github.com/philkra/elastic-apm-php-agent/releases/tag/7.0.0-rc3

**Comment by philkra** [comment]
feel free to close this issue

**Comment by gustavo-maxmilhas** [comment]
Thank you @philkra .

**Comment by pgross41** [comment]
> Ok, that's the problem. The `6.x` version of the lib only supports the `v1` intake API of the APM server and with the `7.x` release, the `v2` intake API is supported, which also correlates with your APM server version. The lib is currently in an rc state, but will be released this week, see last https://github.com/philkra/elastic-apm-php-agent/releases/tag/7.0.0-rc3

@philkra `7.0.0` ready for a final release? I'm interested in a stable version that uses the `v2` intake API.

**Comment by dstepe** [comment]
@pgross41 We are making progress in moving this package over to a new home. We recently made our first release, though I expect to still find issues and would appreciate more usage and feedback:

https://github.com/nipwaayoni/elastic-apm-php-agent

Can you give that a try and start reporting issues against it?

**Comment by pgross41** [comment]
@dstepe That new version is running without error, I will report issues if they come up. Thanks!
