### ISSUE TITLE
Check for APM server status

### ISSUE THREAD

**Issue by Kusanagi-zz** [philkra/elastic-apm-php-agent#111]
Hello everyone.

First thanks for developing this it's really helpful.

Second I have an issue I need to fix and I can't get around it, the problem is that if the APM server fails, the whole application simply stops, and this is unbearable, I need to place a check on the server before hand so that _destruct is not sent and crashes the application with an exception.

Any help or tips for this is greatly appreciated.

I think this issue relates to what I need but I'm not capable of doing anything with it

(https://github.com/philkra/elastic-apm-laravel/issues/9)

**Comment by philkra** [comment]
Hi,

> I need to place a check on the server before hand so that _destruct is not sent and crashes the application with an exception.

you need to be aware that this will slow down your application as it adds another HTTP request every time.

BUT, if you want to go down that path you can use the `info` endpoint of the APM server, see [example](https://github.com/philkra/elastic-apm-php-agent/blob/master/docs/examples/server-info.php). You can `catch it` if an exception is thrown and check the status code to be in the `200` range.

**Comment by Kusanagi-zz** [comment]
Thanks for the reply

I tried that and created a flag variable in order to use the "startTransaction" but from what I see there's a "destruct" call from the agent at the end of my function which I can't catch and the exception still happens

I'll attach a simple code example to illustrate

public function apmTest(){
	$agent = new \PhilKra\Agent($config);
	$apmUp = true;

	try{
		$info = $agent->info();
	} catch (\GuzzleHttp\Exception\ConnectException $e){
		  $apmUp = false;
	}


	if($apmUp !== false)	
		$transaction = $agent->startTransaction('APM Test');
		
	//More PHP Code
		
	if($apmUp !== false)
		$agent->stopTransaction($transaction->getTransactionName());
}

**Comment by philkra** [comment]
Hmm, I see! A suggestion I could offer is the following:

```php
public function apmTest(){
	$agent = new \PhilKra\Agent($config);

	try {
		$info = $agent->info();
	} 
         catch (\GuzzleHttp\Exception\ConnectException $e){
             // disable the agent agent
             $config['active'] = false;
             $agent = new \PhilKra\Agent($config);
	}

	$transaction = $agent->startTransaction('APM Test');
		
	//More PHP Code
		
	$agent->stopTransaction($transaction->getTransactionName());
}
```

You could _simply_ disable the agent and re-create the class, see the [config](https://github.com/philkra/elastic-apm-php-agent/blob/master/docs/config.md). 
In this case the agent will just do a `noop` in the `__destruct` call back. You also don't have to check if the agent is able to connect to the APM server as all traces are just destroyed at the end of PHP's request lifecycle.

**Comment by Kusanagi-zz** [comment]
Tried this solution, but when you create a new Agent, the previous one calls for the destructor and it then falls into the same exception again

**Comment by philkra** [comment]
of course, this happens! sorry haven't tested the code. worst case scenario is to add another try-catch block around the `$agent = new \PhilKra\Agent($config);`.

in order to manipulate the agent at run-time, is to add the functionality to the agent. That would require to expose a method e.g. `Agent::disable()` to mutate the `active` field in `Config` to false. As `Helper\Config` does not have a mutator method by design, it would require a mutator method as well to bubble up the state change. 
Would you be interested in adding a PR for that?

**Comment by Kusanagi-zz** [comment]
I solved it this way:

The config ```active``` is set to _false_ then used a bare Http call to verify the status of the server, then resetting the variable to _true_ and everything works fine for now.

```
$client = new \GuzzleHttp\Client($config['httpClient']);
try{
                  $response = $client->get(
                  $config['serverUrl'],
                  ['headers' => [
                        'Content-Type'     => 'application/x-ndjson',
                        'Accept'           => 'application/json',
                        'Authorization'    => sprintf('Bearer %s', $config['secretToken'])

                ]
                ]
                );
                  if($response->getStatusCode() >= 200){
                          $config['active'] = true;

                  }

          } catch (\GuzzleHttp\Exception\ConnectException $e) {
          }
```

**Comment by philkra** [comment]
TBH, I have a bit of mixed feelings towards your solution ..

another way to prevent exceptions is to leverage the `send` method of the agent. At the end of your script exec, you call
```php
try {
    $agent->send();
}
except(Throwable $t) {
     // ... 
}
```
In that case all payloads were flushed and the destruct of the class _should_ not be fatal. Mind giving that a try?
