### ISSUE TITLE
Send test data to APM Server

### ISSUE THREAD

**Issue by Haddad1** [philkra/elastic-apm-php-agent#114]
Hello everyone,

So i got the apm server up and running, but im just not sure how to send data to it. This is an test code that i have but i feel like im missing something but i dont know what it is:

```
<?php
require 'vendor/autoload.php';

$config = [
    'appName'     => 'APM Test Server',
    'appVersion'  => '1.0',
    'serverUrl'   => 'http://apm-server-ip:8200',
    'hostname'    => 'APM Test Server',
    'env'         => ['DOCUMENT_ROOT'],
];
$agent = new PhilKra\Agent($config);
$transaction = $agent->startTransaction('Simple Transaction');

echo "hello";
sleep(5);
echo "goodbye";
$agent->stopTransaction($transaction->getTransactionName());
```

i assume that after the transaction is stopped the agent should send the data to the apm server and then ES would index it, no?

if not how can i check that the data was actually sent?

Thanks in advance for any help!

**Comment by philkra** [comment]
Use this [example](https://github.com/philkra/elastic-apm-php-agent/blob/master/docs/examples/server-info.php) to fetch the server info to confirm the APM server is running.

Other than that:
* make sure the APM server is running
* same for Elasticsearch
* check that APM server can reach Elasticsearch
* check the APM server logs 

You should use Kibana's APM UI to view the APM traces.

**Comment by MitulShah1** [comment]
@philkra 
When i am trying to get server info using [example](https://github.com/philkra/elastic-apm-php-agent/blob/master/docs/examples/server-info.php)

I get below error.

**Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to 127.0.0.1 port 8200**

Even i tried with my linux IP.

Also its working on my terminal **curl -i 127.0.0.1:82001**

**Comment by philkra** [comment]
please note that your working example `curl -i 127.0.0.1:82001` uses port `82001` and the [example](https://github.com/philkra/elastic-apm-php-agent/blob/master/docs/examples/server-info.php) uses the default which is port `8200`. Please adapt the config array which the k-v `'serverUrl' => 'http://127.0.0.1:82001'` and refer to the [configuration](https://github.com/philkra/elastic-apm-php-agent/blob/master/docs/config.md) guide.

**Comment by MitulShah1** [comment]
Thanks @philkra
