### ISSUE TITLE
How can I get the data of apm-services?【apm server7.4】

### ISSUE THREAD

**Issue by chenzhaozheng** [philkra/elastic-apm-php-agent#115]
How can I get the data of apm-services?
---
environment:

kibana7.4
es7
apm server7.4
elastic-apm-php-agent  7.0.0-rc3

---
$config = [
            'appName'     => 'test',
            'appVersion'  => '1.0.0',
            'serverUrl'   => 'http://10.2.114.101:8200',
            'secretToken' => '',
            'hostname'    => 'APM Server',
            'env'         => ['DOCUMENT_ROOT'],
        ];
        try {
            $agent = new \PhilKra\Agent($config);
            echo "hello";
            sleep(5);
            echo "goodbye";
            $info = $agent->info();
            var_dump($info->getStatusCode());
            var_dump($info->getBody());
        } catch (\GuzzleHttp\Exception\ConnectException $e){
            // disable the agent agent
            $config['active'] = false;
            $agent = new \PhilKra\Agent($config);
        }
        $transaction = $agent->startTransaction('APM Test');

---
Never get data
The result of the request result is 202
I don't know if it is a problem with apm server, or a problem with code, or a problem with Intake API. It is difficult to detect. I can't see the problem when I read the source code.
----
I think the documentation is not comprehensive enough, only at the code level.

**Comment by philkra** [comment]
If you get a `202` HTTP status code as response, the communication between this library and the APM server is fine. You need to investigate that the APM server is able to _talk_ to Elasticserach. I recommend consulting the [Install and run](https://www.elastic.co/guide/en/apm/get-started/current/install-and-run.html) page for ensuring your deployment is correct.

Closing this issue as it's not related to this project.

**Comment by chenzhaozheng** [comment]
The apm service of my nodejs application is successful, I can get the data, and the prompt is very complete, the log record. But php-agent is not working, so I want to know if it is a problem with the premise environment.

**Comment by chenzhaozheng** [comment]
> If you get a `202` HTTP status code as response, the communication between this library and the APM server is fine. You need to investigate that the APM server is able to _talk_ to Elasticserach. I recommend consulting the [Install and run](https://www.elastic.co/guide/en/apm/get-started/current/install-and-run.html) page for ensuring your deployment is correct.
> 
> Closing this issue as it's not related to this project.

The apm service of my nodejs application is successful, I can get the data, and the prompt is very complete, the log record. But php-agent is not working, so I want to know if it is a problem with the premise environment.

**Comment by philkra** [comment]
Consult the [examples](https://github.com/philkra/elastic-apm-php-agent#examples) to make sure you are using the lib correctly.

**Comment by chenzhaozheng** [comment]
> Consult the [examples](https://github.com/philkra/elastic-apm-php-agent#examples) to make sure you are using the lib correctly.

The code I wrote has been sent, it is the above, the case I have tested many times, the v1 and v2 versions of the example are mixed together, some methods are not, so I used the simplest method, but did not show APM Services.

**Comment by philkra** [comment]
the code you wrote is not correct, please use the examples as baseline to ensure that the agent is sending data.

**Comment by chenzhaozheng** [comment]
> the code you wrote is not correct, please use the examples as baseline to ensure that the agent is sending data.

ok,I tested it

----
Example of a Transaction
This example illustrates how you can monitor a call to another web service.

$agent = new \PhilKra\Agent([ 'appName' => 'examples' ]);

$endpoint = 'https://acme.com/api/';
$payload  = [ 'foo' => 'bar' ];
$client   = new GuzzleHttp\Client();

// Start the Transaction
$transaction = $agent->startTransaction('POST https://acme.com/api/');

// Do the call via curl/Guzzle e.g.
$response = $client->request('POST', $endpoint, [
    'json' => $payload
]);

// Stop the Transaction tracing, attach the Status and the sent Payload
$agent->stopTransaction($transaction->getTransactionName(), [
    'status'  => $response->getStatusCode(),
    'payload' => $payload,
]);

// The collected traces will be send to the APM server as soon as
// the Agent object is destroyed. But, you can manually flush the
// playload queue with $agent->send();

---

This case is directly reported
cURL error 7: Failed to connect to 127.0.0.1 port 8200: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
It is a low version of the case

Which of the examples can be displayed to apm service ui? Something that is decisive.
Or a simple case can also let the user perceive that apm has been tuned.
 Thanks.

**Comment by philkra** [comment]
what is the IP/URI of _your_ server?

**Comment by chenzhaozheng** [comment]
> what is the IP/URI of _your_ server?

my server is http://121.46.29.36:8200
Are you going to debug it?

**Comment by chenzhaozheng** [comment]
> what is the IP/URI of _your_ server?
Can you help me see it?

**Comment by chenzhaozheng** [comment]
> what is the IP/URI of _your_ server?

Can you help me see it?

**Comment by philkra** [comment]
you need to use that as `serverUrl` in the config. 

```php
$agent = new \PhilKra\Agent([
  'appName' => 'examples',
  'serverUrl' => 'http://121.46.29.36:8200',
]);
```

**Comment by chenzhaozheng** [comment]
> you need to use that as `serverUrl` in the config.
> 
> ```
> $agent = new \PhilKra\Agent([
>   'appName' => 'examples',
>   'serverUrl' => 'http://121.46.29.36:8200',
> ]);
> ```

I have tried many ways and it won't work. You can access the service, can you help me try it? If you can do that, it is my problem.

**Comment by chenzhaozheng** [comment]
> you need to use that as `serverUrl` in the config.
> 
> ```
> $agent = new \PhilKra\Agent([
>   'appName' => 'examples',
>   'serverUrl' => 'http://121.46.29.36:8200',
> ]);
> ```

Your explanation is powerless, because the documents I have read all, the problem is that there is no way to debug the data.

**Comment by philkra** [comment]
do have elasticsearch and kibana running? you can "debug" the data in kibana, using the APM UI.

**Comment by chenzhaozheng** [comment]
> do have elasticsearch and kibana running? you can "debug" the data in kibana, using the APM UI.

Yes, I don't know how to debug APM. No information in Discover.

**Comment by philkra** [comment]
I'm sorry, but I can not help you any further. Please, consult the documentation.
