### ISSUE TITLE
can i help you?

### ISSUE THREAD

**Issue by gueroverde** [philkra/elastic-apm-php-agent#12]
Do you have a roadmap of activities?

**Comment by philkra** [comment]
@gueroverde, there is no roadmap. yet, feel free to participate. Something that I would like to tackle in the future is the usage of queues like RabbitMQ, Kafka, SQS et al in combination with a lambda function that sends the data. Is that something you want to participate?

**Comment by gueroverde** [comment]
yes @philkra sounds great, I want to participate, how do we coordinate?
