### ISSUE TITLE
Time spent by span type chart is empty

### ISSUE THREAD

**Issue by jremerich** [philkra/elastic-apm-php-agent#123]
Hi!

How do I do to see data on **Time spent by span type** chart?

I'm using the node client and it shows data correctly. I've tried see on it what I need to put on transactions and span to get it, but I didn't get luck.

Here what I talking about:
https://www.elastic.co/guide/en/kibana/7.x/transactions.html

Thanks!

**Comment by science695** [comment]
This agent does not currently support that new feature in Elastic.

See issue https://github.com/philkra/elastic-apm-php-agent/issues/120
