### ISSUE TITLE
APM agent not found error

### ISSUE THREAD

**Issue by gauravpareekk** [philkra/elastic-apm-php-agent#127]
Hey! Thank you for such a unique integration because kibana isn't providing an official integration with php and it seems you've done the job! 

I've been trying to make this work with custom php. I've installed the module with composer. I'm trying one of your examples with this code

```
<?php
require 'vendor/autoload.php'; 
use PhilKra\Agent;

$config = [
    'appName'     => 'APM Test Server',
    'appVersion'  => '1.0',
    'serverUrl'   => 'http://remoteserverip:8200',
    'hostname'    => 'APM Server',
    'env'         => ['DOCUMENT_ROOT'],
];

$agent = new Agent($config);

$info = $agent->info();
?>
```

But it keeps throwing error that info() method not defined in PhilKra\Agent. Am I missing something?

I will be thankful of your help. I'm using php7.1 and my kibana APM server is on a remote IP and accessible with curl http://remoteserverip:8200

**Comment by science695** [comment]
Hello @gauravpareekk, the info function was added in the v7 beta, and the standard composer require Philkra\Agent only installs 6.5.8

Try forcing composer to use version 7.0.0-rc3:

> composer require philkra/elastic-apm-php-agent@7.0.0-rc3

**Comment by gauravpareekk** [comment]
Hey @science695 this command worked for me

> composer require philkra/elastic-apm-php-agent:^7.0.0-rc3

Thanks a lot for the help :) That resolved my issue.
