### ISSUE TITLE
Compatibile issue

### ISSUE THREAD

**Issue by bachciu** [philkra/elastic-apm-php-agent#128]
Hi 
Today i tried to include your package to my project and i have compatibility issue.
On https://packagist.org/packages/philkra/elastic-apm-php-agent is info about requires and there is info about ralouphie/getallheaders: 3.* but when i do composer require philkra/elastic-apm-php-agent i get information :

philkra/elastic-apm-php-agent 6.5.8 requires ralouphie/getallheaders 2.0.5 -> satisfiable by ralouphie/getallheaders[2.0.5] but these conflict with your requirements or minimum-stability.

In my project i use php 7.4, slim 4.4 and ralouphie/getallheaders 3.0.3

Can you update package ralouphie/getallheaders to > 3.0 ?

**Comment by science695** [comment]
Try using the latest version, its marked as beta, but I haven't had any problems with it:

> composer require philkra/elastic-apm-php-agent:^7.0.0-rc3

**Comment by bachciu** [comment]
AWESOME it works :) can you tell me when you plan production version :??
