### ISSUE TITLE
Compatibility with OpenDistro ELK

### ISSUE THREAD

**Issue by Haddad1** [philkra/elastic-apm-php-agent#129]
Hello @philkra,

Quick question, not sure if you know about this but OpenDistro have their own version of the ELK stack which has a bit of differences compared to the original ELK stack. And alot of the original apps such as metricbeat, filebeat, etc.. are not compatible with the OpenDistro version so an OpenDistro version of them was made.

So my question to you is that, is this version of the PHP Agent compatible with OpenDistro or not?

Thanks!

**Comment by philkra** [comment]
This lib is only compatible with the APM server of Elastic.
