### ISSUE TITLE
Include response status code

### ISSUE THREAD

**Issue by felix-lessoer** [philkra/elastic-apm-php-agent#130]
The agent is not collecting the information about the status code automatically.
Is there a way to add it?

**Comment by arkaitzgarro** [comment]
It can be done using the `$transaction->setMeta` method.

https://github.com/philkra/elastic-apm-laravel/blob/master/src/Middleware/RecordTransaction.php#L62L65

**Comment by tsantos84** [comment]
I've found a possible bug when sending response data to APM server. I've just open the PR #133 to fix that. Could you check, please?
