### ISSUE TITLE
setContext method is missing from span

### ISSUE THREAD

**Issue by vanadar** [philkra/elastic-apm-php-agent#131]
Hello, the documentation refers to the method `setContext` for span (for example, in a db.mysql.query, used to push the statement) but the method has been removed ( #122  )

I don't see how i should attach these information to my span now... Are you sure this method had to be removed ?

**Comment by science695** [comment]
@vanadar My Understanding is it is not removing the get/set context functions, but removing the extra non-functional versions, and letting it inherit the standard functions from the EventBean class.

You should still be able to call $span->setContex... its just the function is defined in a more generic class.

**Comment by phoenixgao** [comment]
Right now it's not possible to set context to span, the getContext() function inherited from EventBean filtered the array keys, so fields like `db`, `http` defined in https://github.com/elastic/apm/blob/master/docs/agents/agent-development.md#http-client-spans got dropped.

Also I think we need add a subType to span
