### ISSUE TITLE
Error in composer require lib

### ISSUE THREAD

**Issue by matheusevangelista** [philkra/elastic-apm-php-agent#132]
When I try to install the package in my project it presents the following error:

<img width="1174" alt="Captura de Tela 2020-04-09 às 11 17 50" src="https://user-images.githubusercontent.com/8569794/78905229-094b6900-7a54-11ea-9c5c-844e1cae522b.png">

**Comment by tsantos84** [comment]
I know that is not a best practice, but I'm using the last RC version to get rid of this error.

**Comment by science695** [comment]
@philkra What needs to be done before the 7rc3 branch could become a full release? Do you need testers? are there more updates you want to finish before?

**Comment by tsantos84** [comment]
I'm also interested to know about next major release.

**Comment by supermiro** [comment]
+1

**Comment by dstepe** [comment]
@supermiro This package is being deprecated. Please check out https://github.com/nipwaayoni/elastic-apm-php-agent
