### ISSUE TITLE
Span is not indexed when stacktrace is set

### ISSUE THREAD

**Issue by phoenixgao** [philkra/elastic-apm-php-agent#135]
In the current implementation of `Traits/Events/Stacktrace.php::getDebugBacktrace()`
The value of `vars` is an array with numeric indexes, but APM expect vars as an object, so if a span with stacktrace is sent to APM it get completely lost.

**Comment by dstepe** [comment]
It is true that `vars` is an object, but is property of stacktrace frame:

https://github.com/elastic/apm-server/blob/master/docs/spec/stacktrace_frame.json#L59

A stacktrace is defined as an array with the items of type stacktrace frame:

https://github.com/elastic/apm-server/blob/master/docs/spec/spans/span.json#L206

Please validate that you are generated the correct structure before sending.
