### ISSUE TITLE
Package maintenance proposal

### ISSUE THREAD

**Issue by dstepe** [philkra/elastic-apm-php-agent#136]
I’ve been a casual contributor to this project and now have need of a stable release to work with Elastic APM v7+. Rather than continuing to place the burden on @philkra to own this, I propose that the package be moved to a GitHub organization where interested people can build a community to maintain it.

If this gets traction, I am happy to get the process started. If are interested, please comment on this issue and we’ll go from there. This will be my first GitHub organization and attempt to build a community maintained project. Please bear with me if I seem to go slow and take small steps. I think we can build some great on top of the work already done on this package.

**Comment by philkra** [comment]
@dstepe , it would be great if we could get this lib to an org 👍 I'm more than happy to point to the organisation from this repo!

**Comment by dstepe** [comment]
I've created an organization and forked this repo into it. I'll be upfront and say that I don't have time to take full responsibility for the project so I'll be looking for some interested individuals to start helping with it. 

The project can be found at:

https://github.com/nipwaayoni/elastic-apm-php-agent

I selected the name nipwaayon which means "knowledge, science" in the native language of the Miami Tribe of Oklahoma. 

I'd like to invite people here to work on the project. Open an issue on the new project if you are interested.

**Comment by tsantos84** [comment]
Is there an easy way to move a PR to there?

**Comment by dstepe** [comment]
@tsantos84 I'm not sure about the PR itself. Would it work to create a fork of the new project, add it to your local working copy as a new remote and push your branch to it? Then a new PR should work.

**Comment by ecourtial** [comment]
@dstepe I did a small contibution too. I am also expecting for new developments and features (and most of it, a stable version). So I would like to join your organisation too :)

**Comment by dstepe** [comment]
@ecourtial If you are interested in having a more active role in the organization, let me know and I'll send you an invite. I'm new to running an org and am not exactly sure how to set everything up, but we'll figure it out.

In the meantime, I could help testing the 7.1-dev branch. I'm currently updating the documentation in response to the move to PSR-18 and introduction of an AgentBuilder. I hope to have that merged to dev tomorrow some time.

https://github.com/nipwaayoni/elastic-apm-php-agent

Happy to take questions on that project's issue list.

**Comment by ecourtial** [comment]
@dstepe  Perfect, I am waiting for your invitation then :)

**Comment by FloSew** [comment]
@dstepe To be clear, and as I am not familiar with organizations in github, which lib should I use? this one here (philkra) or nipwaatoni?

**Comment by dstepe** [comment]
The only impact of the organization for consumers is to prevent publishing the package from an individual. It makes it easier to share the maintenance and ownership with others over time.

The philkra version is now deprecated. The new package under the nipwaayoni namespace is published to packagist:

https://packagist.org/packages/nipwaayoni/elastic-apm-php-agent

You will want to use it in your applications:

```
composer require nipwaayoni/elastic-apm-php-agent
```

Don't forget to remove the philkra version if you previously installed it.

**Comment by FloSew** [comment]
Thanks for the clarification. Maybe philkra/elastic-apm-php-agent should be noted as deprecated then in both github and packagist?
