### ISSUE TITLE
Agent setup

### ISSUE THREAD

**Issue by dibmartins** [philkra/elastic-apm-php-agent#22]
Hello everyone, I already installed the package via composer, but I have some doubts:

1 - Where I get "appName" within APM?
2 - Where do I set the url to point to my APM server?

**Comment by philkra** [comment]
hi @dibmartins , 

1 - there is no explicit accessor for the appName, you should use `$config` in the Agent class, which is of type `Config`. With `$this->config->get('appName')` you will able to retrieve the name.

2 - you're right this should be documented better. Please checkout the `Config` helper, https://github.com/philkra/elastic-apm-php-agent/blob/master/src/Helper/Config.php#L61 At the server URL and other configs (as highlighted on L61) can be passed in the `Agent::__construct(array)`

Cheers,
P
