### ISSUE TITLE
Restricting env settings from being passed to APM

### ISSUE THREAD

**Issue by jblotus** [philkra/elastic-apm-php-agent#27]
Hey again,

It would be nice to be able to restrict certain ENV settings from being sent to the APM. Right now the .env files seem to load everything into $_SERVER by default per: 
https://github.com/laravel/framework/issues/18492

https://github.com/philkra/elastic-apm-php-agent/blob/506e2162f33b30f3baade23fe3be375a524e2139/src/Events/EventBean.php#L202

**Comment by philkra** [comment]
@jblotus would you mind having a look at the pr #28 aka the `dev` if that is what you are looking for? You are now able to define which `$_SERVER` values you want to transmit in the env section.

**Comment by jblotus** [comment]
I think it looks great! Yes this would allow being able to whitelist env variables that get sent.

**Comment by philkra** [comment]
great, thanks for the review! I will merge the PR then, thanks for your input!
