### ISSUE TITLE
DateTime::createFromFormat returns FALSE sometimes

### ISSUE THREAD

**Issue by code-in-progress** [philkra/elastic-apm-php-agent#3]
So, this one is interesting. It's not a bug in your code, per se, but more of a PHP issue. When calling line 54 in /Events/EventBean.php, sometimes \DateTime::createFromFormat() returns FALSE and will throw an exception into the errors logs with the message "Call to a member function setTimeZone() on boolean".

After doing some research on it I came across https://bugs.php.net/bug.php?id=64414 (Bug #64414 | DateTime::createFromFormat() fails randomly when using microtime(true) as input). The reason I'm seeing is that sometimes microtime(true) will return a float with only an integer part.

It looks like it's still an open bug in PHP7.x as well. I changed my code to the following to see if this fixes it:

```
$timestamp = \DateTime::createFromFormat( 'U.u', sprintf("%.6F", microtime(true)));
$timestamp->setTimeZone( new \DateTimeZone( 'UTC' ) );
$this->timestamp = $timestamp->format( 'Y-m-d\TH:i:s.u\Z' );
```

Just a heads up in case you run into this.

**Comment by philkra** [comment]
I can across this issue in the test suits and could not dig deeper. This is great! Thanks for the suggested fix. I will make sure it's pushed soon.

**Comment by code-in-progress** [comment]
No worries mate! Team effort. :) It had me boggled for DAYS as well! LOL

So far, no more of those errors have shown up since I made the fix.

**Comment by Ragnoroct** [comment]
This issue saved me LOTS of time 🙌 

This sometimes threw me the error "cannot call format on bool"
```php
DateTime::createFromFormat("U.u", microtime(true), new DateTimeZone('UTC'))->format("Y-m-d\TH:i:s.v");
// Error : Call to a member function format() on bool
```

Easy way to replicate bug
```php
DateTime::createFromFormat("U.u", 1234.00, new DateTimeZone('UTC'))->format("Y-m-d\TH:i:s.v");
// Error : Call to a member function format() on bool
```

**Easy fix** (from OP)
```php
echo DateTime::createFromFormat("U.u", sprintf("%.6F", 1234.00), new DateTimeZone('UTC'))->format("Y-m-d\TH:i:s.v");
// 1970-01-01T00:20:34.000
```
