### ISSUE TITLE
Feature: Redact / sanitize cookies

### ISSUE THREAD

**Issue by jblotus** [philkra/elastic-apm-php-agent#30]
https://github.com/philkra/elastic-apm-php-agent/blob/bc77b79bcc4547177192bd28280cb48cb3cb89a8/src/Events/EventBean.php#L225

Ran into issues where I have jwt tokens stored using cookies and that info is being sent off to the APM. While hunting around to see how other agents handled this I came across this pull request for the go agent.  Also I had to make sure I wasn't sending HTTP_AUTHORIZATION and HTTP_COOKIE via 'env' configuration.

https://github.com/elastic/apm-agent-go/pull/55/commits/fad1cecb39a894efb408836aa2eebdb2854c2de1

At the very least it would be cool to prevent sending cookies at all, based on user configuration. I do like the approach they took to use a user-configurable regex as well.

Thoughts?

**Comment by philkra** [comment]
hi, that does make sense! it should be something similar as the masking of the env vars (https://github.com/philkra/elastic-apm-php-agent/pull/28)

feel free to make a PR :)

**Comment by philkra** [comment]
Done with PR #45
