### ISSUE TITLE
V2 support

### ISSUE THREAD

**Issue by jcalonso** [philkra/elastic-apm-php-agent#34]
Are there plans to support the intake API aka v2?
https://www.elastic.co/guide/en/apm/server/6.5/upgrading-to-65.html

**Comment by philkra** [comment]
yes, there are plans, but I can't give you a timeline yet. The support will be a bigger chunk of rework on the agent side.

**Comment by jcalonso** [comment]
Ok, good to know is on the roadmap, thanks! :)
