### ISSUE TITLE
Duration is 1000 times the value it should be

### ISSUE THREAD

**Issue by pinoniq** [philkra/elastic-apm-php-agent#39]
When stopping a transaction, you use a Timer to calculate the duration of the transaction. You have a toMicro function that does:

```
/**
     * Convert the Duration from Seconds to Micro-Seconds
     *
     * @param  float $num
     *
     * @return float
     */
    private function toMicro(float $num) : float
    {
        return $num * 1000000;
    }
```

This is 1000 to much and it makes the kibana apm think my transactions take 1000seconds.

Is this related to kibana updating something? Or intended?
I'm whiling to open a MR for this.

**Comment by philkra** [comment]
ey caramba! that really seems like a lot! I need to investigate this a little deeper. Out of curiosity, what APM, Kibana and PHP version are you using?

**Comment by pinoniq** [comment]
kibana apm 6.6. (latest version) and php7.2

**Comment by dstepe** [comment]
I'm using APM 6.5 and I'm not seeing this issue. I've only been using APM for a couple of weeks, but your problem with the duration sounds like something I recall hitting at one point. I'm not seeing that behavior and I'm using the same agent code. I've done some digging and haven't been able to find a clear answer regarding the duration value expectations. This proposal may provide the clue, though:

https://github.com/elastic/apm/issues/2

"Today the `duration` property is in milliseconds, but can represent microseconds using decimals:
1.234ms = 1234us"

The implication is that you may have a different experience using an integer than when using a decimal value. I'm explicitly casting to an int and my duration values are correct. I won't have time to test using a decimal value today, but maybe someone else can?

I also found quite a bit about the v2 intake API and it sounds like there will be work that needs to be done in the agent. Are there plans for supporting v2?

**Comment by dstepe** [comment]
Disregard my previous comment. I'm working on two projects with APM, one using just this library and one using the Laravel library built on top of this one. The Laravel durations and correct but the other is x1000. It looked correct relatively and I just didn't pay close enough attention.

I dug around and found that the Laravel library uses a different `getDuration` method in the RecordTransaction class:

```php
    protected function getDuration($start): float
    {
        $diff = microtime(true) - $start;
        $corrected = $diff * 1000; // convert to miliseconds

        return round($corrected, 3);
    }
```
Where the `$start` is the set to the microtime() value at the start of the request processing.

This library Timer class uses:

```php
    public function getDuration() : float
    {
        ...
        return $this->toMicro($this->stoppedOn - $this->startedOn);
    }
    ...
    private function toMicro(float $num) : float
    {
        return $num * 1000000;
    }
```

So I think it is indeed multiplying by and extra 1000.

Part of what threw me off is that I'm using a separate timer and explicitly setting the transaction duration. I noticed that the Transaction::stop() method will quietly cast its value to an int. So when I did this:

```php
$transaction->stop($this->timer->getDuration());
```

The `float` returned by Timer::getDuration() will end up cast to an int in Transaction::stop():

```php
    public function stop(int $duration = null)
    {
        // Stop the Timer
        $this->timer->stop();

        // Store Summary
        $this->summary['duration']  = $duration ?? round($this->timer->getDuration(), 3);
        $this->summary['headers']   = (function_exists('xdebug_get_headers') === true) ? xdebug_get_headers() : [];
        $this->summary['backtrace'] = debug_backtrace();
    }
```
I don't think that's related to this issue, but it would be good for that to be consistent.

**Comment by philkra** [comment]
@dstepe , I guess you found the solution to this! The `1000` factor is too much!

On a side note: I want to point out that the client been tested until APM server `6.4`, so I can't guarantee that the client is working properly on for `6.5` and above.

**Comment by philkra** [comment]
The PR #40 with the fix was merged

**Comment by dstepe** [comment]
@philkra Thanks for accepting this. We're just getting started with APM and have version 6.5. I'm really grateful to have this and the Laravel library available, so thank you. Other than this duration issue, I've not noticed any other problems. I plan to keep working on both of them.
