### ISSUE TITLE
Allow Timer::__construct to accept a start time

### ISSUE THREAD

**Issue by dstepe** [philkra/elastic-apm-php-agent#48]
The Timer class only starts the timer when Timer::start() is explicitly called and uses the current microtime(). Allowing the caller to give a suitable start time in the constructor and start the timer will facilitate using the Timer class when the desired start time precedes the creation of the Timer object. For example, this would allow using the PHP provided `REQUEST_TIME_FLOAT` value.

The Transaction and Agent classes would also be updated to support this optional parameter.

I'm going to work on this in support of possible changes in the Laravel APM timing.

**Comment by philkra** [comment]
can be closed due PR #49
