### ISSUE TITLE
Spans / Traces?

### ISSUE THREAD

**Issue by thinkspill** [philkra/elastic-apm-php-agent#5]
Hi! Thanks for starting this project!

I'm curious if you have plans to handle Spans / Traces?

**Comment by philkra** [comment]
instrumentation is in the pipeline, I actually started but it's suuuuper alpha state. Furthermore, was the plan to include an instrumented library, very likely predis in the next release/tag.

**Comment by thinkspill** [comment]
Awesome! I'd be happy to test it out, whatever stage it may be.

Also, while it doesn't sound like Elastic APM is currently adopting it, there is a standard for APM tracing called OpenTracing which is used in projects like Zipkin and Jaeger. If you're not familiar with it, it may be worth a read: [OpenTracing](http://opentracing.io/) [OpenTracing PHP](https://github.com/opentracing/opentracing-php).

**Comment by georgeboot** [comment]
Support for spans has been added yesterday (#10)

**Comment by philkra** [comment]
Thank you @georgeboot

**Comment by aftabnaveed** [comment]
Sorry for my ignorance, but is it the same thing as this?

https://www.elastic.co/guide/en/apm/get-started/6.5/distributed-tracing.html

Thanks

**Comment by georgeboot** [comment]
@aftabnaveed yes it is

**Comment by aftabnaveed** [comment]
Great! thank you.

**Comment by aftabnaveed** [comment]
@georgeboot is there any documentation available for how to use it? I have a view micro service that I need to benchmark with the laravel microservice. 

Thank you

**Comment by aftabnaveed** [comment]
Yes I did try it and I don't see any traces of my view service. I am using the guzzle client post data to it. 

here is the screenshot: 
![image](https://user-images.githubusercontent.com/58515/51895984-9716d780-23ff-11e9-8550-a9f68fd41840.png)

**Comment by philkra** [comment]
can you confirm that you are using the APM server `6.5.x`, Elasticsearch `6.5.x` and Kibana `6.5.x` ?

**Comment by aftabnaveed** [comment]
Yes I am using Elastic cloud and the latest version of it which is v6.5.4

![image](https://user-images.githubusercontent.com/58515/51897064-f70e7d80-2401-11e9-8ccb-c58b66e42a02.png)

Thank you.
