### ISSUE TITLE
explanation how agent send to apm server

### ISSUE THREAD

**Issue by ynuyasha** [philkra/elastic-apm-php-agent#51]
Hi,
as i read inside code seems that agent send data to apm with guzzle.
This are synchronous calls?
If APM Server goes down, php script that include agent become slowly? 
Or data are sent maybe when register_shutdown_function is called to simulate an async call?

**Comment by philkra** [comment]
Hi @ynuyasha , yes the data is transmitted synchronously. If the APM server is not reachable, the agent will abort after the timeout is reached. So yes, the agent slows down the whole application.

Of course you can invoke the agent's `send()` method with `register_shutdown_function` if you want to. When you send the traces is up to the implementation.

_As a foot note:_ when you are cautious of a possible outage of the APM server, you should run "it" clustered behind a load balancer, https://www.elastic.co/guide/en/apm/server/current/high-availability.html

**Comment by dstepe** [comment]
I believe the handling of the final `send()` is an implementation decision and can be addressed in a number of possible ways. It might be good to note this in the README, but I'm not convinced it is the responsibility of the package to provide a solution.

**Comment by philkra** [comment]
I second that it should be stated better in the README. I‘ll leave this issue open until the more elaborate ˋsend()ˋ explanation

**Comment by philkra** [comment]
Closing due no more Feedback
