### ISSUE TITLE
Timeout on send if server is unavailable

### ISSUE THREAD

**Issue by SelecaoSerasaConsumidor** [philkra/elastic-apm-php-agent#59]
Hello. Im having an issue when i send a transaction and APM server is not available. How i can set a timeout on request?

**Comment by dstepe** [comment]
The package uses the GuzzleHTTP client and provides access to the client configuration in the `$config['httpClient']`. 

https://github.com/philkra/elastic-apm-php-agent#example-of-an-extended-configuration

The best suggestions would be to pass the `timeout` value as shown in the GuzzleHTTP docs:

http://docs.guzzlephp.org/en/stable/quickstart.html#making-a-request

**Comment by philkra** [comment]
Thank you @dstepe  for moderating and giving the solution
