### ISSUE TITLE
APM 6.2 errors

### ISSUE THREAD

**Issue by hotrush** [philkra/elastic-apm-php-agent#6]
Hi, seems your awesome package is some out of date.

Check please this payload https://www.elastic.co/guide/en/apm/server/master/transaction-api.html#payload-with-transactions

- looks like app section renamed to service
- user/custom/tags moved out of transaction section to a context section

Can make a PR if you will accept it

**Comment by philkra** [comment]
hey, thanks for the heads up! i guess there will be many changes to come since elastic's APM is still pretty new. Yeah, go ahead and make a PR!

**Comment by philkra** [comment]
@hotrush this is fixed now with the agent release `6.2.0` https://github.com/philkra/elastic-apm-php-agent/releases/tag/6.2.0

**Comment by hotrush** [comment]
HI @philkra, thanks a lot. I made my own form with some additional features that i need.
