### ISSUE TITLE
Hello from Elastic

### ISSUE THREAD

**Issue by watson** [philkra/elastic-apm-php-agent#60]
Hi @philkra 

My name is Thomas and I'm a developer of the Node.js agent for Elastic APM. I just wanted to reach out and say that I really appreciate the work you've put into this agent.

I just added you to [this list](https://github.com/elastic/apm-contrib#community-developed-agents) we're maintaining of community developed agents. I hope that's ok with you 🙂

If you ever run into any issues with the APM Server API or have any questions regarding these things, don't hesitate to reach out. For example regarding supporting the new v2 API. You can always open an issue in https://github.com/elastic/apm or even just tag me in PR's or issues in this repo and I'll do my best to help.

Also, if you [DM me on Twitter](https://twitter.com/wa7son) with your postal address, I want to send you a little something 📦☺️ If you don't have Twitter, let me know.

**Comment by philkra** [comment]
Hi @watson ,
I‘m don‘t mind at all that the agent is on the list :) thank you very much, I‘m really proud! 
The plan is to tackle ˋv2ˋ in the next 3-4 weeks and get ready for ˋv7.0ˋ of the apm server, thanks a lot for the support!
I don‘t have twitter, but feel free to shoot me an email to philip@philipkrauss.at
