### ISSUE TITLE
Set framework name and version

### ISSUE THREAD

**Issue by shabananavas** [philkra/elastic-apm-php-agent#67]
Currently, I don't think the Agent supports passing the framework name and version to Elastic.

![image](https://user-images.githubusercontent.com/11439056/55214506-ef5e3000-521c-11e9-9ff5-e8304e2dc323.png)

**Comment by philkra** [comment]
can you please provide your config?

**Comment by shabananavas** [comment]
This is what I'm passing to the Agent:

![image](https://user-images.githubusercontent.com/11439056/55224239-19701c00-5236-11e9-907a-648752a00ab9.png)

**Comment by philkra** [comment]
ok, this is something that we need to improve in the documentation, if you want to set a framework name and version, you need to add this in the config array, example:
```php
$config = [
    // other config ...
    'framework' => 'Framework Name',
    'frameworkVersion' => 'Framework Version',
];
$agent = new Agent( $config );
```

can you please verify that this works?

**Comment by shabananavas** [comment]
Yup, that adds it! So, just need to update the documentation.
