### ISSUE TITLE
Elastic APM > 7.0 support

### ISSUE THREAD

**Issue by gomex** [philkra/elastic-apm-php-agent#77]
I can't use my APM server version 7.0.

I am getting this error:

[2019-05-08 18:17:18] local.ERROR: GuzzleHttp\Exception\ClientException: Client error: POST https://myserver.apm.us-east-1.aws.cloud.es.io/v1/transactions resulted in a 404 Not Found response: 404 page not found

According to this doc this endpoint was deprecated: https://www.elastic.co/guide/en/apm/server/7.0/transaction-endpoint.html

We need to change this endpoint request to event API: https://www.elastic.co/guide/en/apm/server/7.0/events-api.html

**Comment by philkra** [comment]
@gomex the `v1` APM endpoints are removed with Elastic's APM server 7+, either you downgrade to APM server `6.7` or kindly wait until the support for `v2` is implemented.

**Comment by nmike** [comment]
what plans for `v2` support? And how we can help your plans came true?

**Comment by philkra** [comment]
this branch contains the starting ground: https://github.com/philkra/elastic-apm-php-agent/tree/6.7.x

the release will have breaking changes to the current lib releases and there will be no support for `v1` anymore. 

The main changes is that each event is now created by a factory, this event object is then registered again in the agent, e.g. `$agent->register($span);`. In case of the suggested socket connection, every register signal should flush out the event.

*TODO's:*
[X] Metrics
[ ] Metadata (75% impl.)
[ ] Transactions (60% implemented of the specs)
[ ] Spans (60% impl. of the specs)
[ ] Errors (0%)
[ ] Sending via sockets (0%)
[X] Sending via Http
[ ] Tests (25%)
[X] Distributed Tracing

**Comment by philkra** [comment]
This is a demo of the implemented features to date:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhilKra\Agent;

// Metricset Demo
use PhilKra\Traces\Metricset\Metric;
use PhilKra\Traces\SpanContexts\Http;

$config = [
    'name' => 'demo',
    'version' => '2.6.23',
    'transport' => [
        'host' => 'http://host.docker.internal:8200',
    ],
    'framework' => [
        'name' => 'foo',
        'version' => '1.2.3',
    ],
];

$contexts = [
  'user' => [
    'id'    => 12345,
    'email' => 'email@acme.com',
    'username' => 'foobar',
  ],
  'tags' => [
      // todo
  ],
];

$agent = new Agent( $config, $contexts );

// Metricset Demo
$metrics = $agent->factory()->newMetricset();
$metrics->put(new Metric('app.metric.a', 12345));
$metrics->put(new Metric('my.super.metric', 42));
//$agent->register($metrics);

// Generate Transaction
$transaction = $agent->factory()->newTransaction('www.heartbeater', 'http.request');
$transaction->setTraceId($transaction->generateTraceId());

$transaction->start();
//

// Send Span
$span = $agent->factory()->newSpan('GET /apm', 'http.request');
//$span->setTraceId($span->generateTraceId());
$span->setTransaction($transaction);
$span->setParentId($span->generateId());

$span->addContext(new Http("http://www.elastic.co/apm", 200, "GET"));

$span->start();

// do some things ...
usleep(rand(1000, 9000));

$span->stop();

$agent->register($span);

// Register Transaction
$agent->register($transaction);

// Flusher
var_dump($agent->send());
```

**Comment by dstepe** [comment]
@philkra I wanted to check in with you on the v2 work. I've not been able to put any attention to APM for several weeks, but I know I'll need to start preparing for our 7.0 upgrade, and hence the need for v2 support, soon. How's it going? Are there specific issues I can help with?

**Comment by philkra** [comment]
closing because of PR #82
