### ISSUE TITLE
Distributed tracing

### ISSUE THREAD

**Issue by ricco24** [philkra/elastic-apm-php-agent#79]
It is possible to set trace.id for distributed tracing?

**Comment by philkra** [comment]
working on it 😄 I expect `v2` to go out soon PR #83

**Comment by philkra** [comment]
with the release of the Agent's rc1, distributed tracing is available, please refer to the [example](https://github.com/philkra/elastic-apm-php-agent/blob/master/docs/examples/distributed-tracing.md) for more informations. closing issue
