### ISSUE TITLE
Symfony support

### ISSUE THREAD

**Issue by murilolobato** [philkra/elastic-apm-php-agent#8]
Does this agent has Symfony integration in its roadmap? 

I'm quite new to Elastic APM, but I saw on online docs for Node.JS and Python agents, that they have out-of-the-box support for most common frameworks, and this mean that it automatically instruments the app automatically.

From what I saw, this PHP agent does not have any automatic framework instrumentation, yet. Right?

**Comment by khal3d** [comment]
+1

**Comment by coudenysj** [comment]
@philkra I would love to help to make this happen.

**Comment by philkra** [comment]
@coudenysj great! I wasn't planing on having a specific framework support, but ahead. Please, create a folder and the adjacent namespace Middleware for the Symfony support via a PR. Thanks!

**Comment by georgeboot** [comment]
For what it's worth, I'm building one for [Laravel](https://github.com/entryninja/elastic-apm-laravel).

**Comment by philkra** [comment]
hi @georgeboot, I did the same thing the last days :) yet, I must admit yours looks more complete with the database traces.
