### ISSUE TITLE
How to handle kafka messages?

### ISSUE THREAD

**Issue by supermiro** [philkra/elastic-apm-php-agent#80]
Hi, what is th best practice to handle traces of Kafka, lets  say we have some producer who is producing messages and probably sending some trace-id in header. My application is producer and I want to know this information and use it in other calls I need to create... Do we have some example for that?

for Kafka messages is used rdkafka library

**Comment by philkra** [comment]
I'm not sure I understand your intentions, you want to backtrace the producers in the subscribers? Is  distributed tracing what you want to achieve?

**Comment by supermiro** [comment]
Hi, yes, I want to achieve distributed tracing. However I am not sure if it
will works in php stack.

st 24. 7. 2019 o 11:43 Philip Krauss <notifications@github.com> napísal(a):

**Comment by philkra** [comment]
Ok, I'm still not sure what kafka has to with it? You want to publish a message in a kafka queue, you can trace that. Then you can trace the consumption and the subsequential action. What can distributed tracing do for you here?

**Comment by supermiro** [comment]
Well, in case that I have microsercice architecture of 100 microservices
which ste mostly communicating via kafka I have pretty big problém with
tracking bugs... And again, for Java I have sleuth library (
https://cloud.spring.io/spring-cloud-sleuth/reference/html/), for PHP I am
not sure...

Miro

Dňa pi, 16. aug 2019, 20:30 Philip Krauss <notifications@github.com>
napísal(a):

**Comment by philkra** [comment]
Closing because it's releated to distributed tracing and hence duplicate to https://github.com/philkra/elastic-apm-php-agent/issues/79
