### ISSUE TITLE
APM v2 plan

### ISSUE THREAD

**Issue by alash3al** [philkra/elastic-apm-php-agent#81]
Thank you for your efforts in this package, I want to ask you about your plans for `APM` `v2` API, and if you need any help in the development so we can accelerate it as possible as we can, I know that there is a `v2` branch, but I don't know what is the current state of it now.

**Comment by Pidz-b** [comment]
I would gladly help if you need extra hands to finish this :)

**Comment by mabdelfattah** [comment]
@watson ☝️

**Comment by alash3al** [comment]
Hi man,

I know that you may be very busy,

I forked the package and did some updates, and it worked [https://github.com/speakol-ads/elastic-apm-php-agent](https://github.com/speakol-ads/elastic-apm-php-agent) if that is ok, just tell me and I'll create a branch for that and send a PR for you,

Note: I did that with the laravel version too [https://github.com/speakol-ads/elastic-apm-laravel](https://github.com/speakol-ads/elastic-apm-laravel),

I wanted to keep its api as it, as well as making it supports the v2, I'll wait for feedback from you,

**Comment by philkra** [comment]
@alash3al , I had started on `v2` ([link](https://github.com/philkra/elastic-apm-php-agent/issues/77#issuecomment-494791186)) but life got in my way. I'm very sorry to left the community hanging! Thanks a lot for fork!!! I created the branch: `v2-support`, please issue a PR against that branch. thanks a ton for your effort ❤️ 🚀

**Comment by philkra** [comment]
Closing because of PR #82
