### ISSUE TITLE
Upgrade version of dependency ralouphie/getallheaders

### ISSUE THREAD

**Issue by ernestobaezf** [philkra/elastic-apm-php-agent#85]
Im trying to install this package using Laravel 5.8 and I get the following error:

> philkra/elastic-apm-php-agent 6.5.3 requires ralouphie/getallheaders 2.0.5 -> satisfiable by ralouphie/getallheaders[2.0.5] but these conflict with your requirements or minimum-stability

**Comment by philkra** [comment]
closing because of PR #88
