### ISSUE TITLE
Why xdebug is required?

### ISSUE THREAD

**Issue by roeehershko** [philkra/elastic-apm-php-agent#9]
i understand that this library is not for production, but using xdebug functions is really making this work only locally

EDIT:
i saw that there is really only 1 use of it, which is "xdebug_get_headers"
i can make a PR to replace it with "headers_list" i think they are pretty much doing the same, then you can remove xdebug dependency

**Comment by philkra** [comment]
Hi, yeah I was playing around with xdebug. Correct, `xdebug_get_headers` is the only use, go ahead and make a PR for xdebug replacement. Thanks!
