### ISSUE TITLE
[SUGGESTION] Allow env config to be supplied a list of $_SERVER keys to exclude

### ISSUE THREAD

**Issue by SurveyGizmoOfficial** [philkra/elastic-apm-php-agent#91]
In addition to being able to specify an inclusive list of keys to send to ELK from $_SERVER, it would be convenient to define a list of keys to exclude, instead.

Currently, as a workaround, I must do the following:

```
new \PhilKra\Agent([
...
	'env' => array_diff(array_keys($_SERVER), ['key-one', 'key-two'])
...
```

**Comment by philkra** [comment]
I understand your need, but this a special use case that does not reflect the general interest. I'm sorry but this feature request will not be implemented.
