### ISSUE TITLE
[SUGGESTION] Allow cookies to be completely omitted

### ISSUE THREAD

**Issue by SurveyGizmoOfficial** [philkra/elastic-apm-php-agent#92]
In addition to being able to specify an inclusive list of keys to send to ELK from $_COOKIE, it would be appreciated to implement a mechanism that excludes all cookies

Currently, as a workaround, I must do the following:

```
new \PhilKra\Agent([
...
	'cookies' => [''],
...
```
Due to the `empty()` state being used as an 'all available' option.

**Comment by philkra** [comment]
do you have a suggestion how the config should look like in order to omit the all cookies? it's required to have an init of `cookies` because otherwise it's a breaking change.

**Comment by philkra** [comment]
no response, closing
